export const PWD_REGEX = /^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#$%.,;]).{8,24}$/
export const EMAIL_REGEX = /^[a-zA-z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/;

export const PRODUCT = {
    id: "",
    name: "",
    category: "",
    slug: [ "" ],
    description: "",
    price: 0,
    dp: "",
    images: [ '' ],
    variation: [ {
      type: "",
      price: "",
      variant: "",
      quantity: ""
    } ],
    merchant_id: "",
    quantity: 0,
    discount_type: "",
    discount_amount: 0,
    opening_date: "",
    available_till: 0,
    delivery_duration: 0,
    dispatch_location: "",
    unit: "",
    product_type: "",
    inStock: false,
    createdAt: "",
    updatedAt: "",
    suplementryProducts: [ {
      "id": "",
      "name": "",
      "product_id": "",
      "quantity": 12,
      "price": 3000,
      "dp": ""
    }]
}
  

export const CARTITEM = {
  id: "", // Generated by server when saved in DB; otherwise, null for local items
  productId: "", // ID from the original product
  name: "",
  variation: {
    type: "",
    variant: "",
    price: 0,
    quantity: 0,
  },
  suplementryProducts: [
    {
      id: "", // Supplementary product ID
      name: "",
      price: 0,
      quantity: 0,
    },
  ],
  quantity: 1, // Total quantity for this cart item
  price: 0, // Price of selected variation
  total: 0, // (itemPrice * quantity) + supplementary products’ total
};
